<?php
return [
  'en' => [
    'login' => 'Login',
    'password' => 'Password',
    'password_onetime' => 'Link-Password',
    'wrong_password' => 'Wrong password',
    'too_many_attempts' => 'Too many login attempts.',
    'you_have_been_blocked' => 'You have been blocked for 10 minutes.',
    'new' => 'New',
    'logout' => 'Logout',
    'content' => 'Content',
    'attachment' => 'Attachment',
    'add' => 'Add',
    'add_secret' => 'Add Secret',
    'show_secret' => 'Show Secret',
    'something_went_wrong' => 'Something went wrong. Please contact the person who sent you this link immediately!',
    'bar_info' => 'This content is only visible to you and can only be opened once.<br>Do <strong>not</strong> close the window before you have read and copied the content<br>and downloaded the attachment (if any).',
    'download' => 'Download',
    'link' => 'Onetime-Password-Link',
    'copy' => 'Copy',
    'copy_to_clipboard' => 'Copy content to clipboard',
    'cookies_required' => 'Your browser is blocking necessary first party session <strong>cookies</strong>. Please enable this cookie and reload the page.',
    'notify_enable' => 'Send notification when secret is opened',
    'notification_id' => 'Notification ID',
    'email_notification_subject' => 'BAR secret opened by: %s',
    'email_notification_body' => 'The BAR secret with ID %s has been successfully opened at %s.',
  ],
  'de' => [
    'login' => 'Anmelden',
    'password' => 'Passwort',
    'password_onetime' => 'Link-Passwort',
    'wrong_password' => 'Falsches Passwort',
    'too_many_attempts' => 'Zu viele Anmeldeversuche.',
    'you_have_been_blocked' => 'Sie wurden für 10 Minuten gesperrt.',
    'new' => 'Neu',
    'logout' => 'Abmelden',
    'content' => 'Inhalt',
    'attachment' => 'Anhang',
    'add' => 'Hinzufügen',
    'add_secret' => 'Geheimnis hinzufügen',
    'show_secret' => 'Geheimnis anzeigen',
    'something_went_wrong' => 'Etwas ist schiefgelaufen. Bitte melden Sie sich umgehend bei demjenigen, der Ihnen diesen Link gesendet hat!',
    'bar_info' => 'Dieser Inhalt ist nur für Sie sichtbar und kann nur einmal geöffnet werden.<br>Schließen Sie das Fenster <strong>nicht</strong>, bevor Sie den Inhalt gelesen und kopiert, sowie den Anhang (falls vorhanden) heruntergeladen haben.',
    'download' => 'Herunterladen',
    'link' => 'Einmal-Passwort-Link',
    'copy' => 'Kopieren',
    'copy_to_clipboard' => 'Inhalt in die Zwischenablage kopieren',
    'cookies_required' => 'Ihr Browser blockiert notwendige Erstanbieter-Session-<strong>Cookies</strong>. Bitte aktivieren Sie dieses Cookie und laden Sie die Seite neu.',
    'notify_enable' => 'Benachrichtigung senden, wenn Geheimnis geöffnet wird',
    'notification_id' => 'Benachrichtigungs-ID',
    'email_notification_subject' => 'BAR Geheimnis geöffnet von: %s',
    'email_notification_body' => 'Das BAR Geheimnis mit der ID %s wurde am %s erfolgreich geöffnet.',
  ],
];