<?php
return [
  'en' => [
    'login' => 'Login',
    'password' => 'Password',
    'wrong_password' => 'Wrong password',
    'too_many_attempts' => 'Too many login attempts.',
    'you_have_been_blocked' => 'You have been blocked for 10 minutes.',
    'content' => 'Content',
    'attachment' => 'Attachment',
    'add' => 'Add',
    'add_secret' => 'Add Secret',
    'show_secret' => 'Show Secret',
    'something_went_wrong' => 'Something went wrong. Please contact the person who sent you this link immediately!',
    'bar_info' => 'This content is only visible to you and can only be opened once.<br>Do not close the window before you have read the content and downloaded the attachment (if any).',
    'download' => 'Download',
    'link' => 'Link',
  ],
  'de' => [
    'login' => 'Anmelden',
    'password' => 'Passwort',
    'wrong_password' => 'Falsches Passwort',
    'too_many_attempts' => 'Zu viele Anmeldeversuche.',
    'you_have_been_blocked' => 'Sie wurden für 10 Minuten gesperrt.',
    'content' => 'Inhalt',
    'attachment' => 'Anhang',
    'add' => 'Hinzufügen',
    'add_secret' => 'Geheimnis hinzufügen',
    'show_secret' => 'Geheimnis anzeigen',
    'something_went_wrong' => 'Etwas ist schiefgelaufen. Bitte melden Sie sich umgehend bei demjenigen, der Ihnen diesen Link gesendet hat!',
    'bar_info' => 'Dieser Inhalt ist nur für Sie sichtbar und kann nur einmal geöffnet werden.<br>Schließen Sie das Fenster nicht, bevor Sie den Inhalt gelesen und den Anheng (falls vorhanden) heruntergeladen haben.',
    'download' => 'Herunterladen',
    'link' => 'Link',
  ],
];